[project]
authors = ["ecamo19 <erickcamo19@gmail.com>"]
channels = ["conda-forge"]
description = "This file contains all the dependencies for reproducing the statistical analisys for the paper title: "
name = "physiolocal_responses_tropical_dry_forest_reproducible_stats"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
rstudio = { cmd = "rstudio"}
[dependencies]
r = "<=4.4.1"
r-dplyr = ">=1.1.4,<2"
r-car = ">=3.1_3,<4"
r-rmarkdown = ">=2.28,<3"
r-emmeans = ">=1.10.5,<2"
r-tidyverse = ">=2.0.0,<3"
r-nlme = ">=3.1_165,<4"
r-ggpubr = ">=0.6.0,<0.7"
r-ggsci = ">=3.2.0,<4"
r-here = ">=1.0.1,<2"
r-janitor = ">=2.2.0,<3"
r-knitr = ">=1.48,<2"
r-reactablefmtr = ">=2.0.0,<3"
r-prettydoc = ">=0.4.1,<0.5"
