[project]
authors = ["ecamo19 <erickcamo19@gmail.com>"]
channels = ["conda-forge"]
description = "This file contains all the dependencies for reproducing the statistical analisys for the paper title:Physiological and growth responses of tropical dry forest tree seedlings to water and nutrient additions: comparisons between nitrogen fixers and non-fixers"
name = "physiolocal_responses_tropical_dry_forest_reproducible_stats"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
# This is for Linux distros
rstudio = { cmd = "rstudio"}

[dependencies]
r = ">=4.1.1,<4.4.1"
r-dplyr = ">=1.1.4,<2"
r-car = ">=3.1_3,<4"
r-rmarkdown = ">=2.28,<3"
r-emmeans = ">=1.10.5,<2"
r-tidyverse = ">=2.0.0,<3"
r-nlme = ">=3.1_165,<4"
r-ggpubr = ">=0.6.0,<0.7"
r-ggsci = ">=3.2.0,<4"
r-here = ">=1.0.1,<2"
r-janitor = ">=2.2.0,<3"
r-knitr = ">=1.48,<2"
r-reactablefmtr = ">=2.0.0,<3"
r-prettydoc = ">=0.4.1,<0.5"
r-readxl = ">=1.4.3,<2"
r-lme4 = ">=1.1_35.5,<2"
r-performance = ">=0.12.4,<0.13"
jupyterlab = ">=4.3.1,<5"
r-irkernel = ">=1.3.2,<2"
pixi-kernel = ">=0.5.1,<0.6"
r-dichromat = ">=2.0_0.1,<3"
pip = ">=24.3.1,<25"
ipython = ">=8.29.0,<9"
ipywidgets = ">=8.1.5,<9"
python = "==3.10"
notebook = ">=6.5.7,<7"
bash_kernel = ">=0.7.2,<0.10"

